on: push
jobs:
  write-to-bucket:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup Vault
      run: |-
        set -euo pipefail

        VAULT_VERSION=1.12.3
        wget -q https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
        unzip vault_${VAULT_VERSION}_linux_amd64.zip -d ~/
    - name: Generate GSA key
      run: |
        set -euo pipefail
        
        export VAULT_ADDR=${{ secrets.VAULT_ADDR }}
        JWT=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL| jq -r '.value')
        export VAULT_TOKEN=$(~/vault write auth/github-jwt/login -format=json role=github jwt=$JWT | jq -r '.auth.client_token')
        ~/vault read gcp/static-account/bucket-admin/key -format=json | jq -r .data.private_key_data | base64 -d > svc.json
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Create file
      run: |-
        set -euo pipefail
        gcloud auth login --cred-file=svc.json
        F="test.$RANDOM"
        echo "Creating $F"
        echo "Testing 123" > $F
        gsutil cp $F gs://${{ secrets.GCS_BUCKET_NAME }}/
        gsutil cat gs://${{ secrets.GCS_BUCKET_NAME }}/$F
