name: lint
on:
  push:
jobs:
  run:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4
      with:
        terraform_version: 1.5.7

    - name: lint
      run: terraform fmt **/*.tf
