name: Create release

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read
  pull-requests: read

jobs:
  release:
    if: >-
      github.event.pull_request.merged == true &&
      (contains(github.event.pull_request.title, '[major]') ||
      contains(github.event.pull_request.title, '[minor]') ||
      contains(github.event.pull_request.title, '[patch]'))
    uses: libops/.github/.github/workflows/bump-release.yaml@main
    permissions:
      contents: write
      actions: write
